name: CI Pipeline

# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

# Define the job
jobs:
  build_tests:
    name: Build
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22 # Specify the Node.js version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run tests
      - name: Run build tests
        run: npx mocha --grep '@build'
        if: ${{ !cancelled() }}
        with:
        name: build-tests
        path: test-report/
        retention-days: 30

  smoke_tests:
    name: Smoke Tests
    runs-on: ubuntu-latest # Use the latest Ubuntu runner
    needs: build_tests

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22 # Specify the Node.js version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run tests
      - name: Run build tests
        run: npx mocha --grep '@smoke'
        if: ${{ !cancelled() }}
        with:
        name: smoke-tests
        path: test-report/
        retention-days: 30

  regression_tests:
    name: Regression Tests
    runs-on: ubuntu-latest # Use the latest Ubuntu runner
    needs: smoke_tests

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22 # Specify the Node.js version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run tests
      - name: Run regression tests
        run: npx mocha --grep '@regression'
        if: ${{ !cancelled() }}
        with:
        name: regression-tests
        path: test-report/
        retention-days: 30